name: run
run_id: commands[0]
env TERM: xterm-256color
env TMPDIR: /var/folders/d_/fmwppt2s6zdd3hc8y4fvs_km0000gn/T/
env LANG: en_US.UTF-8
env HOME: /Users/albertmends
env PATH: /Users/albertmends/Documents/ecoair/backend/.tox/test_app/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/Users/albertmends/.nvm/versions/node/v21.2.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin
env PYTHONHASHSEED: 3291742227
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env TOX_ENV_NAME: run
env TOX_WORK_DIR: /Users/albertmends/Documents/ecoair/backend/.tox
env TOX_ENV_DIR: /Users/albertmends/Documents/ecoair/backend/.tox/test_app
env VIRTUAL_ENV: /Users/albertmends/Documents/ecoair/backend/.tox/test_app
env COLUMNS: 62
env LINES: 12
metadata pid: 18607
cwd: /Users/albertmends/Documents/ecoair/backend
allow: /Users/albertmends/Documents/ecoair/backend/.tox/test_app/bin/*
cmd: python app/main.py
exit_code: -15
[32mINFO[0m:     ::1:51993 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52021 - "[1mGET /api/v1/manufacturers/get-manufacturers HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52019 - "[1mGET /api/v1/countries/get-countries HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52023 - "[1mGET /api/v1/parameters/get-parameters HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52022 - "[1mGET /api/v1/instruments/get-instruments HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:51993 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52020 - "[1mGET /api/v1/providers/get-providers HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52110 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52250 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52317 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52347 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:52378 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:53515 - "[1mGET /api/v1/locations/get-locations HTTP/1.1[0m" [32m200 OK[0m

standard error:
[32m2024-04-08 09:08:54.629[0m | [33m[1mWARNING [0m | [36m__main__[0m:[36m<module>[0m:[36m60[0m - [33m[1mRunning in development mode. Do not run like this in production.[0m
[32mINFO[0m:     Started server process [[36m18607[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://localhost:8001[0m (Press CTRL+C to quit)
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Finished server process [[36m18607[0m]
[31mERROR[0m:    Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/starlette/routing.py", line 743, in lifespan
    await receive()
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "/Users/albertmends/Documents/ecoair/backend/app/main.py", line 63, in <module>
    uvicorn.run(app, host="localhost", port=8001, log_level="debug")
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    with self.capture_signals():
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/albertmends/Documents/ecoair/backend/.tox/test_app/lib/python3.11/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 157, in _on_sigint
    raise KeyboardInterrupt()
KeyboardInterrupt
